### PR TITLE
Add ratings for IntelliJ-Haskell

### PR DESCRIPTION
**Pull request by chris-martin**
Related issue: #4

Code completion - 🚗 - Doesn't suggest every possible thing, but pretty good for the most part

Error reporting - 🚀 - All errors are correctly highlighted, messages show up in tooltips. Not sure what more I could ask for.

Lint - 🚲 - Hlint works, but is slow https://github.com/rikvdkleij/intellij-haskell/issues/148

Code Format - 🚲 - Supposedly supports hindent and stylish-haskell but I haven't gotten them working

Goto def, find usages - 🚀 - omg amazing

Stepwise Debugger - 🚶 - None that I know of

Doc. tooltips - 🚲 - Works sometimes but not for everything

Snippets - ... - I don't know what this means?

Hoogle - 🚲 - Kind of works, doesn't seem finished

### CODE REVIEW

**Comment by rainbyte** [comment]
Snippets are predefined pieces of code, some included by the plug-in, and you could add more by yourself.
Example: if I write case, it would show the following as possible completion
```
case ___ of
  __ -> ___
```
It is mostly for pieces of code that you write very often.

**Comment by rainbyte** [comment]
Rating were tested using [this plug-in](https://github.com/rikvdkleij/intellij-haskell) right? (Just to be sure before merging)

**Comment by chris-martin** [comment]
Yep, that's the one.

**Comment by rainbyte** [comment]
Merged, thanks!

**Pull request merged**
